project_id = "pmsaearbupcinwukoeeh"

[functions.create-pix-payment]
verify_jwt = false

[functions.track-utmify]
verify_jwt = false

[functions.goatpay-webhook]
verify_jwt = false

[functions.sharkpay-webhook]
verify_jwt = false

[functions.nitropay-webhook]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false